// data.jsx — sample sessions and steps
// Realistic AF-flavored: IMDS, WO-99999, TN-12345, CAC PIN redacted
// All identifiers are obviously-fake

const SESSIONS = [
  {
    id: "ses_2026_04_29_imds_wo",
    name: "IMDS — Create Work Order WO-99999 (TN-12345)",
    captured_at: "2026-04-29T14:32:11Z",
    captured_by: "smith.j.tsgt",
    duration_s: 247,
    event_count: 11,
    classification: "CUI",
    bundle_size: "8.4 MB",
    status: "draft",
  },
  {
    id: "ses_2026_04_28_to_lookup",
    name: "T.O. Lookup — Hydraulic Pressure Test (1F-16C-2-29)",
    captured_at: "2026-04-28T09:14:02Z",
    captured_by: "smith.j.tsgt",
    duration_s: 143,
    event_count: 7,
    classification: "CUI",
    bundle_size: "4.1 MB",
    status: "exported",
  },
  {
    id: "ses_2026_04_25_aris_login",
    name: "ARIS Login + Daily Inspection Sign-off",
    captured_at: "2026-04-25T07:02:48Z",
    captured_by: "lopez.r.ssgt",
    duration_s: 89,
    event_count: 5,
    classification: "CUI",
    bundle_size: "2.6 MB",
    status: "exported",
  },
  {
    id: "ses_2026_04_22_g081_terminal",
    name: "G081 — Terminal Session (TN3270 fallback demo)",
    captured_at: "2026-04-22T11:48:31Z",
    captured_by: "park.h.amn",
    duration_s: 312,
    event_count: 14,
    classification: "CUI",
    bundle_size: "6.9 MB",
    status: "draft",
  },
  {
    id: "ses_2026_04_19_cac_renew",
    name: "CAC Certificate Renewal — ActivClient",
    captured_at: "2026-04-19T13:22:09Z",
    captured_by: "smith.j.tsgt",
    duration_s: 178,
    event_count: 9,
    classification: "CUI",
    bundle_size: "5.2 MB",
    status: "archived",
  },
];

// The active session — IMDS work order. 11 steps, mix of UIA + TN3270 fallback,
// CAC PIN redacted. Each step has a fake screenshot rendered as SVG.
const STEPS = [
  {
    id: "evt_001",
    seq: 1,
    kind: "uia",
    name: "Click on \"IMDS Production\" in Desktop",
    auto_text: "Click on \"IMDS Production\" in Desktop",
    user_text: "",
    timestamp: "14:32:11",
    window_title: "Desktop",
    window_class: "Progman",
    automation_id: "DesktopIcon_IMDSProduction",
    control_type: "ListItem",
    click: { x: 142, y: 218 },
    enabled: true,
    redactions: [],
    screenshot: "desktop",
  },
  {
    id: "evt_002",
    seq: 2,
    kind: "uia",
    name: "Type CAC PIN",
    auto_text: "Type CAC PIN",
    user_text: "Insert CAC and enter PIN at the ActivClient prompt.",
    timestamp: "14:32:24",
    window_title: "ActivClient — PIN Required",
    window_class: "#32770",
    automation_id: "PinEntryBox",
    control_type: "Edit",
    click: { x: 512, y: 380 },
    enabled: true,
    sensitive: true,
    redactions: [{ x: 0.42, y: 0.55, w: 0.22, h: 0.06, label: "PIN" }],
    screenshot: "cac_pin",
  },
  {
    id: "evt_003",
    seq: 3,
    kind: "uia",
    name: "Click on \"Work Orders\" in IMDS — Main Menu",
    auto_text: "Click on \"Work Orders\" in IMDS — Main Menu",
    user_text: "",
    timestamp: "14:32:48",
    window_title: "IMDS — Main Menu",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "btnWorkOrders",
    control_type: "Button",
    click: { x: 320, y: 264 },
    enabled: true,
    redactions: [],
    screenshot: "imds_menu",
  },
  {
    id: "evt_004",
    seq: 4,
    kind: "uia",
    name: "Click on \"New Work Order\" in IMDS — Work Orders",
    auto_text: "Click on \"New Work Order\" in IMDS — Work Orders",
    user_text: "",
    timestamp: "14:33:02",
    window_title: "IMDS — Work Orders",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "btnNewWorkOrder",
    control_type: "Button",
    click: { x: 168, y: 122 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_list",
  },
  {
    id: "evt_005",
    seq: 5,
    kind: "uia",
    name: "Type \"WO-99999\" in Work Order Number",
    auto_text: "Type \"WO-99999\" in Work Order Number",
    user_text: "Enter the work order number assigned by the planner.",
    timestamp: "14:33:31",
    window_title: "IMDS — Work Order Entry",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "txtWorkOrderNumber",
    control_type: "Edit",
    typed_text: "WO-99999",
    click: { x: 412, y: 248 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_entry",
  },
  {
    id: "evt_006",
    seq: 6,
    kind: "uia",
    name: "Type \"TN-12345\" in Tail Number",
    auto_text: "Type \"TN-12345\" in Tail Number",
    user_text: "",
    timestamp: "14:33:48",
    window_title: "IMDS — Work Order Entry",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "txtTailNumber",
    control_type: "Edit",
    typed_text: "TN-12345",
    click: { x: 412, y: 296 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_entry",
  },
  {
    id: "evt_007",
    seq: 7,
    kind: "uia",
    name: "Select \"Hydraulic System\" in WUC dropdown",
    auto_text: "Select \"Hydraulic System\" in WUC dropdown",
    user_text: "",
    timestamp: "14:34:09",
    window_title: "IMDS — Work Order Entry",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "cboWUC",
    control_type: "ComboBox",
    selected_value: "14000 — Hydraulic System",
    click: { x: 412, y: 344 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_entry",
  },
  {
    id: "evt_008",
    seq: 8,
    kind: "tn3270",
    name: "",
    auto_text: "",
    ocr_text: "ENTER REF T.O. NUMBER:",
    user_text: "",
    timestamp: "14:34:42",
    window_title: "G081 Reference Lookup — BlueZone Mainframe",
    window_class: "BZWindowClass",
    automation_id: null,
    control_type: null,
    click: { x: 624, y: 412 },
    enabled: true,
    fallback_reason: "UIA returned empty ElementInfo",
    context_region: { x: 524, y: 352, w: 200, h: 120 },
    redactions: [],
    screenshot: "g081_terminal",
  },
  {
    id: "evt_009",
    seq: 9,
    kind: "tn3270",
    name: "",
    auto_text: "",
    ocr_text: "1F-16C-2-29",
    typed_text: "1F-16C-2-29",
    user_text: "Enter the technical order reference for hydraulic pressure test.",
    timestamp: "14:35:02",
    window_title: "G081 Reference Lookup — BlueZone Mainframe",
    window_class: "BZWindowClass",
    automation_id: null,
    control_type: null,
    click: { x: 624, y: 412 },
    enabled: true,
    fallback_reason: "UIA returned empty ElementInfo",
    context_region: { x: 524, y: 352, w: 200, h: 120 },
    redactions: [],
    screenshot: "g081_terminal_typed",
  },
  {
    id: "evt_010",
    seq: 10,
    kind: "uia",
    name: "Click on \"Attach Reference\" in IMDS — Work Order Entry",
    auto_text: "Click on \"Attach Reference\" in IMDS — Work Order Entry",
    user_text: "",
    timestamp: "14:35:31",
    window_title: "IMDS — Work Order Entry",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "btnAttachRef",
    control_type: "Button",
    click: { x: 540, y: 480 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_entry_full",
  },
  {
    id: "evt_011",
    seq: 11,
    kind: "uia",
    name: "Click on \"Submit\" in IMDS — Work Order Entry",
    auto_text: "Click on \"Submit\" in IMDS — Work Order Entry",
    user_text: "Confirm the entry and submit. The system will assign a control number.",
    timestamp: "14:36:18",
    window_title: "IMDS — Work Order Entry",
    window_class: "WindowsForms10.Window.8.app.0.bf7771_r12_ad1",
    automation_id: "btnSubmit",
    control_type: "Button",
    click: { x: 712, y: 540 },
    enabled: true,
    redactions: [],
    screenshot: "imds_wo_submit",
  },
];

window.AGSOP_DATA = { SESSIONS, STEPS };
